// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: drugAvailability.proto

package com.example.protos;

public final class DrugAvailabilityOuterClass {
  private DrugAvailabilityOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_FindDrugRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_FindDrugRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_FindDrugResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_FindDrugResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_Drug_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_Drug_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_Pharmacy_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_Pharmacy_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026drugAvailability.proto\022\006protos\"/\n\017Find" +
      "DrugRequest\022\016\n\006apiKey\030\001 \001(\t\022\014\n\004name\030\002 \001(" +
      "\t\"/\n\020FindDrugResponse\022\033\n\005drugs\030\001 \003(\0132\014.p" +
      "rotos.Drug\"V\n\004Drug\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002" +
      " \001(\t\022\020\n\010quantity\030\003 \001(\005\022\"\n\010pharmacy\030\004 \001(\013" +
      "2\020.protos.Pharmacy\"$\n\010Pharmacy\022\n\n\002id\030\001 \001" +
      "(\005\022\014\n\004name\030\002 \001(\t2S\n\020DrugAvailability\022?\n\010" +
      "FindDrug\022\027.protos.FindDrugRequest\032\030.prot" +
      "os.FindDrugResponse\"\000B3\n\022com.example.pro" +
      "tosP\001\252\002\032IntegrationAdapters.Protosb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protos_FindDrugRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_FindDrugRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_FindDrugRequest_descriptor,
        new java.lang.String[] { "ApiKey", "Name", });
    internal_static_protos_FindDrugResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protos_FindDrugResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_FindDrugResponse_descriptor,
        new java.lang.String[] { "Drugs", });
    internal_static_protos_Drug_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protos_Drug_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_Drug_descriptor,
        new java.lang.String[] { "Id", "Name", "Quantity", "Pharmacy", });
    internal_static_protos_Pharmacy_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_protos_Pharmacy_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_Pharmacy_descriptor,
        new java.lang.String[] { "Id", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
