// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PharmacySystemApi_Id1.proto

package com.example.protos;

public interface DrugOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Drug)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 quantity = 3;</code>
   * @return The quantity.
   */
  int getQuantity();

  /**
   * <code>string code = 4;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string code = 4;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>.Pharmacy pharmacy = 5;</code>
   * @return Whether the pharmacy field is set.
   */
  boolean hasPharmacy();
  /**
   * <code>.Pharmacy pharmacy = 5;</code>
   * @return The pharmacy.
   */
  com.example.protos.Pharmacy getPharmacy();
  /**
   * <code>.Pharmacy pharmacy = 5;</code>
   */
  com.example.protos.PharmacyOrBuilder getPharmacyOrBuilder();
}
