// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: drugAvailability.proto

package com.example.protos;

public interface DrugOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.Drug)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 quantity = 3;</code>
   * @return The quantity.
   */
  int getQuantity();

  /**
   * <code>.protos.Pharmacy pharmacy = 4;</code>
   * @return Whether the pharmacy field is set.
   */
  boolean hasPharmacy();
  /**
   * <code>.protos.Pharmacy pharmacy = 4;</code>
   * @return The pharmacy.
   */
  com.example.protos.Pharmacy getPharmacy();
  /**
   * <code>.protos.Pharmacy pharmacy = 4;</code>
   */
  com.example.protos.PharmacyOrBuilder getPharmacyOrBuilder();
}
