// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PharmacySystemApi_Id1.proto

package com.example.protos;

/**
 * Protobuf type {@code FindDrugResponse}
 */
public final class FindDrugResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:FindDrugResponse)
    FindDrugResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FindDrugResponse.newBuilder() to construct.
  private FindDrugResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FindDrugResponse() {
    drugs_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FindDrugResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FindDrugResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              drugs_ = new java.util.ArrayList<com.example.protos.Drug>();
              mutable_bitField0_ |= 0x00000001;
            }
            drugs_.add(
                input.readMessage(com.example.protos.Drug.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        drugs_ = java.util.Collections.unmodifiableList(drugs_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.protos.PharmacySystemApiId1.internal_static_FindDrugResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.protos.PharmacySystemApiId1.internal_static_FindDrugResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.protos.FindDrugResponse.class, com.example.protos.FindDrugResponse.Builder.class);
  }

  public static final int DRUGS_FIELD_NUMBER = 1;
  private java.util.List<com.example.protos.Drug> drugs_;
  /**
   * <code>repeated .Drug drugs = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.example.protos.Drug> getDrugsList() {
    return drugs_;
  }
  /**
   * <code>repeated .Drug drugs = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.example.protos.DrugOrBuilder> 
      getDrugsOrBuilderList() {
    return drugs_;
  }
  /**
   * <code>repeated .Drug drugs = 1;</code>
   */
  @java.lang.Override
  public int getDrugsCount() {
    return drugs_.size();
  }
  /**
   * <code>repeated .Drug drugs = 1;</code>
   */
  @java.lang.Override
  public com.example.protos.Drug getDrugs(int index) {
    return drugs_.get(index);
  }
  /**
   * <code>repeated .Drug drugs = 1;</code>
   */
  @java.lang.Override
  public com.example.protos.DrugOrBuilder getDrugsOrBuilder(
      int index) {
    return drugs_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < drugs_.size(); i++) {
      output.writeMessage(1, drugs_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < drugs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, drugs_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.protos.FindDrugResponse)) {
      return super.equals(obj);
    }
    com.example.protos.FindDrugResponse other = (com.example.protos.FindDrugResponse) obj;

    if (!getDrugsList()
        .equals(other.getDrugsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDrugsCount() > 0) {
      hash = (37 * hash) + DRUGS_FIELD_NUMBER;
      hash = (53 * hash) + getDrugsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.protos.FindDrugResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.protos.FindDrugResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.protos.FindDrugResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.protos.FindDrugResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.protos.FindDrugResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.protos.FindDrugResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.protos.FindDrugResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.protos.FindDrugResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.protos.FindDrugResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.protos.FindDrugResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.protos.FindDrugResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.protos.FindDrugResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.protos.FindDrugResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code FindDrugResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:FindDrugResponse)
      com.example.protos.FindDrugResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.protos.PharmacySystemApiId1.internal_static_FindDrugResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.protos.PharmacySystemApiId1.internal_static_FindDrugResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.protos.FindDrugResponse.class, com.example.protos.FindDrugResponse.Builder.class);
    }

    // Construct using com.example.protos.FindDrugResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDrugsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (drugsBuilder_ == null) {
        drugs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        drugsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.protos.PharmacySystemApiId1.internal_static_FindDrugResponse_descriptor;
    }

    @java.lang.Override
    public com.example.protos.FindDrugResponse getDefaultInstanceForType() {
      return com.example.protos.FindDrugResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.protos.FindDrugResponse build() {
      com.example.protos.FindDrugResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.protos.FindDrugResponse buildPartial() {
      com.example.protos.FindDrugResponse result = new com.example.protos.FindDrugResponse(this);
      int from_bitField0_ = bitField0_;
      if (drugsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          drugs_ = java.util.Collections.unmodifiableList(drugs_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.drugs_ = drugs_;
      } else {
        result.drugs_ = drugsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.protos.FindDrugResponse) {
        return mergeFrom((com.example.protos.FindDrugResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.protos.FindDrugResponse other) {
      if (other == com.example.protos.FindDrugResponse.getDefaultInstance()) return this;
      if (drugsBuilder_ == null) {
        if (!other.drugs_.isEmpty()) {
          if (drugs_.isEmpty()) {
            drugs_ = other.drugs_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDrugsIsMutable();
            drugs_.addAll(other.drugs_);
          }
          onChanged();
        }
      } else {
        if (!other.drugs_.isEmpty()) {
          if (drugsBuilder_.isEmpty()) {
            drugsBuilder_.dispose();
            drugsBuilder_ = null;
            drugs_ = other.drugs_;
            bitField0_ = (bitField0_ & ~0x00000001);
            drugsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDrugsFieldBuilder() : null;
          } else {
            drugsBuilder_.addAllMessages(other.drugs_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.protos.FindDrugResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.protos.FindDrugResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.example.protos.Drug> drugs_ =
      java.util.Collections.emptyList();
    private void ensureDrugsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        drugs_ = new java.util.ArrayList<com.example.protos.Drug>(drugs_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.protos.Drug, com.example.protos.Drug.Builder, com.example.protos.DrugOrBuilder> drugsBuilder_;

    /**
     * <code>repeated .Drug drugs = 1;</code>
     */
    public java.util.List<com.example.protos.Drug> getDrugsList() {
      if (drugsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(drugs_);
      } else {
        return drugsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Drug drugs = 1;</code>
     */
    public int getDrugsCount() {
      if (drugsBuilder_ == null) {
        return drugs_.size();
      } else {
        return drugsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Drug drugs = 1;</code>
     */
    public com.example.protos.Drug getDrugs(int index) {
      if (drugsBuilder_ == null) {
        return drugs_.get(index);
      } else {
        return drugsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Drug drugs = 1;</code>
     */
    public Builder setDrugs(
        int index, com.example.protos.Drug value) {
      if (drugsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDrugsIsMutable();
        drugs_.set(index, value);
        onChanged();
      } else {
        drugsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Drug drugs = 1;</code>
     */
    public Builder setDrugs(
        int index, com.example.protos.Drug.Builder builderForValue) {
      if (drugsBuilder_ == null) {
        ensureDrugsIsMutable();
        drugs_.set(index, builderForValue.build());
        onChanged();
      } else {
        drugsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Drug drugs = 1;</code>
     */
    public Builder addDrugs(com.example.protos.Drug value) {
      if (drugsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDrugsIsMutable();
        drugs_.add(value);
        onChanged();
      } else {
        drugsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Drug drugs = 1;</code>
     */
    public Builder addDrugs(
        int index, com.example.protos.Drug value) {
      if (drugsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDrugsIsMutable();
        drugs_.add(index, value);
        onChanged();
      } else {
        drugsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Drug drugs = 1;</code>
     */
    public Builder addDrugs(
        com.example.protos.Drug.Builder builderForValue) {
      if (drugsBuilder_ == null) {
        ensureDrugsIsMutable();
        drugs_.add(builderForValue.build());
        onChanged();
      } else {
        drugsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Drug drugs = 1;</code>
     */
    public Builder addDrugs(
        int index, com.example.protos.Drug.Builder builderForValue) {
      if (drugsBuilder_ == null) {
        ensureDrugsIsMutable();
        drugs_.add(index, builderForValue.build());
        onChanged();
      } else {
        drugsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Drug drugs = 1;</code>
     */
    public Builder addAllDrugs(
        java.lang.Iterable<? extends com.example.protos.Drug> values) {
      if (drugsBuilder_ == null) {
        ensureDrugsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, drugs_);
        onChanged();
      } else {
        drugsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Drug drugs = 1;</code>
     */
    public Builder clearDrugs() {
      if (drugsBuilder_ == null) {
        drugs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        drugsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Drug drugs = 1;</code>
     */
    public Builder removeDrugs(int index) {
      if (drugsBuilder_ == null) {
        ensureDrugsIsMutable();
        drugs_.remove(index);
        onChanged();
      } else {
        drugsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Drug drugs = 1;</code>
     */
    public com.example.protos.Drug.Builder getDrugsBuilder(
        int index) {
      return getDrugsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Drug drugs = 1;</code>
     */
    public com.example.protos.DrugOrBuilder getDrugsOrBuilder(
        int index) {
      if (drugsBuilder_ == null) {
        return drugs_.get(index);  } else {
        return drugsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Drug drugs = 1;</code>
     */
    public java.util.List<? extends com.example.protos.DrugOrBuilder> 
         getDrugsOrBuilderList() {
      if (drugsBuilder_ != null) {
        return drugsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(drugs_);
      }
    }
    /**
     * <code>repeated .Drug drugs = 1;</code>
     */
    public com.example.protos.Drug.Builder addDrugsBuilder() {
      return getDrugsFieldBuilder().addBuilder(
          com.example.protos.Drug.getDefaultInstance());
    }
    /**
     * <code>repeated .Drug drugs = 1;</code>
     */
    public com.example.protos.Drug.Builder addDrugsBuilder(
        int index) {
      return getDrugsFieldBuilder().addBuilder(
          index, com.example.protos.Drug.getDefaultInstance());
    }
    /**
     * <code>repeated .Drug drugs = 1;</code>
     */
    public java.util.List<com.example.protos.Drug.Builder> 
         getDrugsBuilderList() {
      return getDrugsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.protos.Drug, com.example.protos.Drug.Builder, com.example.protos.DrugOrBuilder> 
        getDrugsFieldBuilder() {
      if (drugsBuilder_ == null) {
        drugsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.example.protos.Drug, com.example.protos.Drug.Builder, com.example.protos.DrugOrBuilder>(
                drugs_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        drugs_ = null;
      }
      return drugsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:FindDrugResponse)
  }

  // @@protoc_insertion_point(class_scope:FindDrugResponse)
  private static final com.example.protos.FindDrugResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.protos.FindDrugResponse();
  }

  public static com.example.protos.FindDrugResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FindDrugResponse>
      PARSER = new com.google.protobuf.AbstractParser<FindDrugResponse>() {
    @java.lang.Override
    public FindDrugResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FindDrugResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FindDrugResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FindDrugResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.protos.FindDrugResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

