// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PharmacySystemApi_Id1.proto

package com.example.protos;

public interface OrderDrugRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrderDrugRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string apiKey = 1;</code>
   * @return The apiKey.
   */
  java.lang.String getApiKey();
  /**
   * <code>string apiKey = 1;</code>
   * @return The bytes for apiKey.
   */
  com.google.protobuf.ByteString
      getApiKeyBytes();

  /**
   * <code>int32 idPharmacy = 2;</code>
   * @return The idPharmacy.
   */
  int getIdPharmacy();

  /**
   * <code>int32 idDrug = 3;</code>
   * @return The idDrug.
   */
  int getIdDrug();

  /**
   * <code>int32 quantity = 4;</code>
   * @return The quantity.
   */
  int getQuantity();
}
