// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PharmacySystemApi_Id1.proto

package com.example.protos;

public interface OrderDrugResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrderDrugResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();
}
