// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PharmacySystemApi_Id1.proto

package com.example.protos;

/**
 * Protobuf type {@code OrderDrugRequest}
 */
public final class OrderDrugRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:OrderDrugRequest)
    OrderDrugRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OrderDrugRequest.newBuilder() to construct.
  private OrderDrugRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OrderDrugRequest() {
    apiKey_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OrderDrugRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OrderDrugRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            apiKey_ = s;
            break;
          }
          case 16: {

            idPharmacy_ = input.readInt32();
            break;
          }
          case 24: {

            idDrug_ = input.readInt32();
            break;
          }
          case 32: {

            quantity_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.protos.PharmacySystemApiId1.internal_static_OrderDrugRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.protos.PharmacySystemApiId1.internal_static_OrderDrugRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.protos.OrderDrugRequest.class, com.example.protos.OrderDrugRequest.Builder.class);
  }

  public static final int APIKEY_FIELD_NUMBER = 1;
  private volatile java.lang.Object apiKey_;
  /**
   * <code>string apiKey = 1;</code>
   * @return The apiKey.
   */
  @java.lang.Override
  public java.lang.String getApiKey() {
    java.lang.Object ref = apiKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      apiKey_ = s;
      return s;
    }
  }
  /**
   * <code>string apiKey = 1;</code>
   * @return The bytes for apiKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getApiKeyBytes() {
    java.lang.Object ref = apiKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      apiKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IDPHARMACY_FIELD_NUMBER = 2;
  private int idPharmacy_;
  /**
   * <code>int32 idPharmacy = 2;</code>
   * @return The idPharmacy.
   */
  @java.lang.Override
  public int getIdPharmacy() {
    return idPharmacy_;
  }

  public static final int IDDRUG_FIELD_NUMBER = 3;
  private int idDrug_;
  /**
   * <code>int32 idDrug = 3;</code>
   * @return The idDrug.
   */
  @java.lang.Override
  public int getIdDrug() {
    return idDrug_;
  }

  public static final int QUANTITY_FIELD_NUMBER = 4;
  private int quantity_;
  /**
   * <code>int32 quantity = 4;</code>
   * @return The quantity.
   */
  @java.lang.Override
  public int getQuantity() {
    return quantity_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getApiKeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, apiKey_);
    }
    if (idPharmacy_ != 0) {
      output.writeInt32(2, idPharmacy_);
    }
    if (idDrug_ != 0) {
      output.writeInt32(3, idDrug_);
    }
    if (quantity_ != 0) {
      output.writeInt32(4, quantity_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getApiKeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, apiKey_);
    }
    if (idPharmacy_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, idPharmacy_);
    }
    if (idDrug_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, idDrug_);
    }
    if (quantity_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, quantity_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.protos.OrderDrugRequest)) {
      return super.equals(obj);
    }
    com.example.protos.OrderDrugRequest other = (com.example.protos.OrderDrugRequest) obj;

    if (!getApiKey()
        .equals(other.getApiKey())) return false;
    if (getIdPharmacy()
        != other.getIdPharmacy()) return false;
    if (getIdDrug()
        != other.getIdDrug()) return false;
    if (getQuantity()
        != other.getQuantity()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + APIKEY_FIELD_NUMBER;
    hash = (53 * hash) + getApiKey().hashCode();
    hash = (37 * hash) + IDPHARMACY_FIELD_NUMBER;
    hash = (53 * hash) + getIdPharmacy();
    hash = (37 * hash) + IDDRUG_FIELD_NUMBER;
    hash = (53 * hash) + getIdDrug();
    hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
    hash = (53 * hash) + getQuantity();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.protos.OrderDrugRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.protos.OrderDrugRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.protos.OrderDrugRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.protos.OrderDrugRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.protos.OrderDrugRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.protos.OrderDrugRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.protos.OrderDrugRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.protos.OrderDrugRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.protos.OrderDrugRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.protos.OrderDrugRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.protos.OrderDrugRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.protos.OrderDrugRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.protos.OrderDrugRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code OrderDrugRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:OrderDrugRequest)
      com.example.protos.OrderDrugRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.protos.PharmacySystemApiId1.internal_static_OrderDrugRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.protos.PharmacySystemApiId1.internal_static_OrderDrugRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.protos.OrderDrugRequest.class, com.example.protos.OrderDrugRequest.Builder.class);
    }

    // Construct using com.example.protos.OrderDrugRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      apiKey_ = "";

      idPharmacy_ = 0;

      idDrug_ = 0;

      quantity_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.protos.PharmacySystemApiId1.internal_static_OrderDrugRequest_descriptor;
    }

    @java.lang.Override
    public com.example.protos.OrderDrugRequest getDefaultInstanceForType() {
      return com.example.protos.OrderDrugRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.protos.OrderDrugRequest build() {
      com.example.protos.OrderDrugRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.protos.OrderDrugRequest buildPartial() {
      com.example.protos.OrderDrugRequest result = new com.example.protos.OrderDrugRequest(this);
      result.apiKey_ = apiKey_;
      result.idPharmacy_ = idPharmacy_;
      result.idDrug_ = idDrug_;
      result.quantity_ = quantity_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.protos.OrderDrugRequest) {
        return mergeFrom((com.example.protos.OrderDrugRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.protos.OrderDrugRequest other) {
      if (other == com.example.protos.OrderDrugRequest.getDefaultInstance()) return this;
      if (!other.getApiKey().isEmpty()) {
        apiKey_ = other.apiKey_;
        onChanged();
      }
      if (other.getIdPharmacy() != 0) {
        setIdPharmacy(other.getIdPharmacy());
      }
      if (other.getIdDrug() != 0) {
        setIdDrug(other.getIdDrug());
      }
      if (other.getQuantity() != 0) {
        setQuantity(other.getQuantity());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.protos.OrderDrugRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.protos.OrderDrugRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object apiKey_ = "";
    /**
     * <code>string apiKey = 1;</code>
     * @return The apiKey.
     */
    public java.lang.String getApiKey() {
      java.lang.Object ref = apiKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        apiKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string apiKey = 1;</code>
     * @return The bytes for apiKey.
     */
    public com.google.protobuf.ByteString
        getApiKeyBytes() {
      java.lang.Object ref = apiKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        apiKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string apiKey = 1;</code>
     * @param value The apiKey to set.
     * @return This builder for chaining.
     */
    public Builder setApiKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      apiKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string apiKey = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearApiKey() {
      
      apiKey_ = getDefaultInstance().getApiKey();
      onChanged();
      return this;
    }
    /**
     * <code>string apiKey = 1;</code>
     * @param value The bytes for apiKey to set.
     * @return This builder for chaining.
     */
    public Builder setApiKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      apiKey_ = value;
      onChanged();
      return this;
    }

    private int idPharmacy_ ;
    /**
     * <code>int32 idPharmacy = 2;</code>
     * @return The idPharmacy.
     */
    @java.lang.Override
    public int getIdPharmacy() {
      return idPharmacy_;
    }
    /**
     * <code>int32 idPharmacy = 2;</code>
     * @param value The idPharmacy to set.
     * @return This builder for chaining.
     */
    public Builder setIdPharmacy(int value) {
      
      idPharmacy_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 idPharmacy = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdPharmacy() {
      
      idPharmacy_ = 0;
      onChanged();
      return this;
    }

    private int idDrug_ ;
    /**
     * <code>int32 idDrug = 3;</code>
     * @return The idDrug.
     */
    @java.lang.Override
    public int getIdDrug() {
      return idDrug_;
    }
    /**
     * <code>int32 idDrug = 3;</code>
     * @param value The idDrug to set.
     * @return This builder for chaining.
     */
    public Builder setIdDrug(int value) {
      
      idDrug_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 idDrug = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdDrug() {
      
      idDrug_ = 0;
      onChanged();
      return this;
    }

    private int quantity_ ;
    /**
     * <code>int32 quantity = 4;</code>
     * @return The quantity.
     */
    @java.lang.Override
    public int getQuantity() {
      return quantity_;
    }
    /**
     * <code>int32 quantity = 4;</code>
     * @param value The quantity to set.
     * @return This builder for chaining.
     */
    public Builder setQuantity(int value) {
      
      quantity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 quantity = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantity() {
      
      quantity_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:OrderDrugRequest)
  }

  // @@protoc_insertion_point(class_scope:OrderDrugRequest)
  private static final com.example.protos.OrderDrugRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.protos.OrderDrugRequest();
  }

  public static com.example.protos.OrderDrugRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OrderDrugRequest>
      PARSER = new com.google.protobuf.AbstractParser<OrderDrugRequest>() {
    @java.lang.Override
    public OrderDrugRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OrderDrugRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OrderDrugRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OrderDrugRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.protos.OrderDrugRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

