// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: drugAvailability.proto

package com.example.protos;

public interface PharmacyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.Pharmacy)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
