// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PharmacySystemApi_Id1.proto

package com.example.protos;

public final class PharmacySystemApiId1 {
  private PharmacySystemApiId1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FindDrugRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FindDrugRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FindDrugResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FindDrugResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Drug_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Drug_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Pharmacy_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Pharmacy_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderDrugRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderDrugRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderDrugResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderDrugResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033PharmacySystemApi_Id1.proto\"/\n\017FindDru" +
      "gRequest\022\016\n\006apiKey\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\"(" +
      "\n\020FindDrugResponse\022\024\n\005drugs\030\001 \003(\0132\005.Drug" +
      "\"]\n\004Drug\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\020\n\010qu" +
      "antity\030\003 \001(\005\022\014\n\004code\030\004 \001(\t\022\033\n\010pharmacy\030\005" +
      " \001(\0132\t.Pharmacy\"5\n\010Pharmacy\022\n\n\002id\030\001 \001(\005\022" +
      "\014\n\004name\030\002 \001(\t\022\017\n\007address\030\003 \001(\t\"X\n\020OrderD" +
      "rugRequest\022\016\n\006apiKey\030\001 \001(\t\022\022\n\nidPharmacy" +
      "\030\002 \001(\005\022\016\n\006idDrug\030\003 \001(\005\022\020\n\010quantity\030\004 \001(\005" +
      "\"$\n\021OrderDrugResponse\022\017\n\007success\030\001 \001(\0102{" +
      "\n\020DrugAvailability\0221\n\010FindDrug\022\020.FindDru" +
      "gRequest\032\021.FindDrugResponse\"\000\0224\n\tOrderDr" +
      "ug\022\021.OrderDrugRequest\032\022.OrderDrugRespons" +
      "e\"\000B6\n\022com.example.protosP\001\252\002\035Integratio" +
      "nAdapters.Apis.Grpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_FindDrugRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FindDrugRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FindDrugRequest_descriptor,
        new java.lang.String[] { "ApiKey", "Name", });
    internal_static_FindDrugResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_FindDrugResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FindDrugResponse_descriptor,
        new java.lang.String[] { "Drugs", });
    internal_static_Drug_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Drug_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Drug_descriptor,
        new java.lang.String[] { "Id", "Name", "Quantity", "Code", "Pharmacy", });
    internal_static_Pharmacy_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Pharmacy_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Pharmacy_descriptor,
        new java.lang.String[] { "Id", "Name", "Address", });
    internal_static_OrderDrugRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_OrderDrugRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderDrugRequest_descriptor,
        new java.lang.String[] { "ApiKey", "IdPharmacy", "IdDrug", "Quantity", });
    internal_static_OrderDrugResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_OrderDrugResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderDrugResponse_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
